config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :categories, only: :show

  resources :users, only: [:index, :show, :edit, :update] do

    member do
      get :friend_list
    end

  end

  resources :likes, only: [:create, :destroy]

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy] do

    member do
      post :confirm
    end

  end

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error

  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :request_friend, through: :inverse_friendships, source: :user

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def send_request?(user)
    if self.friends.include?(user)
      self.friendships.find_by(friend_id: user.id).status == "request"
    else
      false
    end
  end

  def be_friend_with?(user)
    if self.friends.include?(user)
      self.friendships.find_by(friend_id: user.id).status == "confirm"
    else
      false
    end
  end

  def unconfirm_friends
    unconfirm_friendships = self.friendships.where(status: "unconfirm")
    unconfirm_friends = []
    unconfirm_friendships.each do |unconfirm_friendship|
      unconfirm_friends << User.find(unconfirm_friendship.friend_id)
    end
    return unconfirm_friends
  end

  def request_friends
    request_friendships = self.friendships.where(status: "request")
    request_friends = []
    request_friendships.each do |request_friendship|
      request_friends << User.find(request_friendship.friend_id)
    end
    return request_friends
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
  end

  def edit
    if current_user != @user
      flash[:alert] = "You are not allow to edit the profile"
      redirect_to user_path(@user)
    end

  end

  def update
    @user.update(user_params)
    flash[:notice] = "user profile was successfully updated"
    redirect_to user_path(@user)
  end

  def friend_list
    @unconfirm_friends = @user.unconfirm_friends
    @request_friends = @user.request_friends
  end

  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name, "名稱" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :intor, "自我介紹" %>
    <%= f.text_area :intro, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar, "大頭貼" %>
    <%= image_tag @user.avatar, width: "300px" if @user.avatar? %>
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <%= f.submit %>
  <%= f.button "Cancel", type: :reset %>
<% end %>

app/views/users/friend_list.html.erb
<div class="container-fluid friend-list-container">
  <% if current_user == @user %>
    <div class="panel panel-default">
      <div class="panel-heading my-panel-heading">
        <h4 class="panel-title"><%= "#{@unconfirm_friends.size} Unconfirm Friends" %></h4>
      </div>
      <div class="panel-body unconfirm-friends">
        <% @unconfirm_friends.each do |unconfirm_friend| %>
          <div>
            <div>
              <div class="follow-img-frame">
                <%= image_tag unconfirm_friend.avatar, class: "img-responsive img-circle" if unconfirm_friend.avatar? %>
                <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
                 class: "img-responsive img-circle" if !unconfirm_friend.avatar?%>
              </div>
              <h5 class="text-center"><%= link_to unconfirm_friend.name, user_path(unconfirm_friend) %></h5>
            </div>
            <div>
              <%= link_to "Confirm", confirm_friendship_path(friend_id: unconfirm_friend.id),
              method: :post, class: "btn btn-default btn-unconfirm" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading my-panel-heading">
      <h4 class="panel-title"><%= "#{@user.friends.size - @unconfirm_friends.size - @request_friends.size} Friends" %></h4>
    </div>
    <div class="panel-body confirm-friends">
      <% @user.friends.each do |friend| %>
        <% if !@unconfirm_friends.include?(friend) && !@request_friends.include?(friend) %>
          <div>
            <div class="follow-img-frame">
              <%= image_tag unconfirm_friend.avatar, class: "img-responsive img-circle" if friend.avatar? %>
              <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
               class: "img-responsive img-circle" if !friend.avatar?%>
            </div>
            <h5 class="text-center"><%= link_to friend.name, user_path(friend) %></h5>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">

  <ul class="nav nav-tabs my-tabs">
    <li role="presentation"><%= link_to "首頁", restaurants_path %></li>
    <li role="presentation"><%= link_to "最新動態", feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to "Top10人氣餐廳", ranking_restaurants_path %></li>
    <li role="presentation" class="active"><%= link_to "美食達人", users_path %></li>
  </ul>
  <br>

  <div class="user-index-container">
    <% @users.each do |user| %>
      <div class="user-index-content">
        <div class="user-index-img-frame">
          <%= image_tag user.avatar, class: "img-responsive" if user.avatar? %>
          <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
         class: "img-responsive" if !user.avatar?%>
        </div>
        <h4><%= link_to user.name, user_path(user) %></h4>
        <div class="user-index-button">
          <div><%= render partial: "shared/follow", locals: {user: user} %></div>
          <div><%= render partial: "shared/friend", locals: {user: user} %></div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="profile-personal-info row">
    <div class="avatar-frame col-sm-3">
      <%= image_tag @user.avatar, class: "img-responsive img-circle" if @user.avatar? %>
      <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
       class: "img-responsive img-circle" if !@user.avatar?%>
    </div>
    <div class="col-sm-9">
      <table>
        <tr>
          <td><h3><%= @user.name %></h3></td>
        </tr>
        <tr>
          <td><h5><b><%= @user.email %></b></h5></td>
        </tr>
        <tr>
          <td><p><%= @user.intro %></p></td>
        </tr>
        <tr>
          <td>
            <%= render partial: "shared/follow", locals: {user: @user} %>
            <%= render partial: "shared/friend", locals: {user: @user} %>
          </td>
        </tr>
      </table>

      <% if current_user == @user %>
        <%= link_to edit_user_path(@user), class: "profile-edit btn btn-default" do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      <% end %>
      <br>
      <%= link_to "好友名單", friend_list_user_path(@user), class: "btn btn-default" %>
    </div>
  </div>

  <br>

  <div class="user-information-container">
    <div class="panel panel-default followings">
      <div class="panel-heading  my-panel-heading">
        <h4 class="panel-title"><%= "#{@user.followings.size} followings" %></h4>
      </div>
      <div class="panel-body">
        <% @user.followings.each do |following| %>
          <div class="follow-img-frame">
            <%= image_tag following.avatar, class: "img-responsive img-circle" if following.avatar? %>
            <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
             class: "img-responsive img-circle" if !following.avatar?%>
          </div>
          <h5 class="text-center"><%= link_to following.name, user_path(following) %></h5>
        <% end %>
      </div>
    </div>


    <div class="panel panel-default commented-restaurants">
      <div class="panel-heading  my-panel-heading">
        <h4 class="panel-title"><%= "#{@commented_restaurants.size} commented restaurants" %></h4>
      </div>
      <div class="panel-body my-restaurant-link">
        <% @commented_restaurants.each do |restaurant| %>
          <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div class="my-restaurant-img-frame">
                <% if restaurant.image? %>
                  <%= image_tag restaurant.image, class: "center-block",
                  height: "100%" %>
                <% else %>
                  <%= image_tag "http://fakeimg.pl/270x180/BBBBBB/", class: "center-block",
                  height: "100%" %>
                <% end %>
              </div>
              <h4 class="text-center"><%= restaurant.name %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default followers">
      <div class="panel-heading  my-panel-heading">
        <h4 class="panel-title"><%= "#{@user.followers.size} followers" %></h4>
      </div>
      <div class="panel-body">
        <% @user.followers.each do |follower| %>
          <div class="follow-img-frame">
            <%= image_tag follower.avatar, class: "img-responsive img-circle" if follower.avatar?%>
            <%= image_tag "http://www.likoda.com.tw/style/images/frontpage/default_user_icon.png",
             class: "img-responsive img-circle" if !follower.avatar?%>
          </div>
          <h5 class="text-center"><%= link_to follower.name, user_path(follower) %></h5>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default favorited-restaurants">
      <div class="panel-heading  my-panel-heading">
        <h4 class="panel-title"><%= "#{@favorited_restaurants.size} favorite restaurants" %></h4>
      </div>
      <div class="panel-body my-restaurant-link">
        <% @favorited_restaurants.each do |restaurant| %>
          <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div class="my-restaurant-img-frame">
                <% if restaurant.image? %>
                  <%= image_tag restaurant.image, class: "center-block",
                  height: "100%" %>
                <% else %>
                  <%= image_tag "http://fakeimg.pl/270x180/BBBBBB/", class: "center-block",
                  height: "100%" %>
                <% end %>
              </div>
              <h4 class="text-center"><%= restaurant.name %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>