config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :categories, only: :show

  resources :users, only: [:index, :show, :edit, :update] do

    member do
      get :friend_list
    end

  end

  resources :likes, only: [:create, :destroy]

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy] do

    member do
      post :confirm
    end

  end

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def update_favorites_count
    self.update(favorites_count: self.favorites.count)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    flash[:notice] = "restaurant was successfullu deleted"
    redirect_to admin_restaurants_path
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours,
      :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new(content: params[:content], score: params[:score])
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    @restaurant.update_favorites_count
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    favorite.destroy_all
    @restaurant.update_favorites_count
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @top10_restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="well">
  <%= form_for [:admin, @restaurant], :html => {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :category_id, "Category", class: "col-xs-1 control-label" %>
    <div class="col-xs-offset-1 col-xs-9">
      <%= f.collection_select :category_id, Category.all, :id, :name,
      {prompt: true}, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, "Name", class: "col-xs-1 control-label" %>
    <div class="col-xs-offset-1 col-xs-9">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel, "Tel", class: "col-xs-1 control-label" %>
    <div class="col-xs-offset-1 col-xs-9">
      <%= f.text_field :tel, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, "Address", class: "col-xs-1 control-label" %>
    <div class="col-xs-offset-1 col-xs-9">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :opening_hours, "Opening Hours", class: "col-xs-2" %>
    <div class="col-xs-9">
      <%= f.text_field :opening_hours, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description", class: "col-xs-1" %>
    <div class="col-xs-12">
      <%= f.text_area :description, class: "form-control description-size" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, "Photo", class: "col-xs-1" %>
    <%= image_tag @restaurant.image, class: "form-image-frame", width: '300px' if @restaurant.image?  %>
    <div class="upload-button">
      <%= f.file_field :image %>
    </div>
  </div>

  <%= f.submit class: "btn btn-danger form-btn-style" %>
  <% end %>
</div>

app/views/admin/restaurants/edit.html.erb
<h1 class="edit-title">Edit Information</h1>
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<h1 class="index-title">Restaurants List</h1>

<%= link_to admin_categories_path, class: "btn btn-default" do %>
  <span class="glyphicon glyphicon-arrow-right"> Categories List</span>
<% end %>
<hr>

<table class="table">
  <tr>
    <td></td>
    <th class="res-category">Category</th>
    <th class="res-name">Name</th>
    <td></td><td></td><td></td>
  </tr>
  <% @restaurants.each do |restaurant| %>
  <tr>
    <td><div class="admin-index-image-frame"><%= image_tag restaurant.image, width: "100%" %></div></td>
    <td><p class=res-category><%= restaurant.category.name %></p></td>
    <td><p class="res-name"><%= restaurant.name %></p></td>
    <td><%= link_to '瀏覽', admin_restaurant_path(restaurant),
      class: "btn btn-default"%></td>
    <td><%= link_to '編輯', edit_admin_restaurant_path(restaurant),
    class: "btn btn-default" %></td>
    <td><%= link_to '刪除', admin_restaurant_path(restaurant),
    class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

<%= paginate @restaurants %>
<%= link_to new_admin_restaurant_path, class: "btn btn-default pull-right" do %>
  <span class="glyphicon glyphicon-plus"></span> Add New Restaurant
<% end %>

app/views/admin/restaurants/new.html.erb
<h1 class="new-title">New Restaurant</h1>
<%= render partial: "form" %>