config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :categories, only: :show

  resources :users, only: [:index, :show, :edit, :update] do

    member do
      get :friend_list
    end

  end

  resources :likes, only: [:create, :destroy]

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy] do

    member do
      post :confirm
    end

  end

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def update_favorites_count
    self.update(favorites_count: self.favorites.count)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    flash[:notice] = "restaurant was successfullu deleted"
    redirect_to admin_restaurants_path
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours,
      :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new(content: params[:content], score: params[:score])
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    @restaurant.update_favorites_count
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    favorite.destroy_all
    @restaurant.update_favorites_count
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @top10_restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<div class="container-fluid">
  <h2><%= @restaurant.name %>'s Dashboard</h2>
  <hr>
  <ul>
    <li>有 <%= @restaurant.comments.count %> 筆評論</li>
    <li>這家餐廳的平均價位為 $XXX</li>
    <li>有 XX 人收藏這家餐廳</li>
  </ul>
</div>

app/views/restaurants/feeds.html.erb
<div class="container-fluid">

  <ul class="nav nav-tabs my-tabs">
    <li role="presentation"><%= link_to "首頁", restaurants_path %></li>
    <li role="presentation" class="active"><%= link_to "最新動態", feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to "Top10人氣餐廳", ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to "美食達人", users_path %></li>
  </ul>
  <br>

  <div class="row">
    <div class="panel panel-default col-sm-6">
      <div class="panel-heading my-panel-heading">
        <div class="panel-title"><h3>最新餐廳</h3></div>
      </div>
      <div class="panel-body feeds-restaurants-panel-body">
        <% @recent_restaurants.each do |restaurant| %>
          <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <p class="label label-default my-label"><%= restaurant.category.name %></p>
          <p><%= restaurant.description %></p>
          <hr>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default col-sm-6">
      <div class="panel-heading my-panel-heading">
        <div class="panel-title"><h3>最新評論</h3></div>
      </div>
      <div class="panel-body feeds-comments-panel-body">
        <% @recent_comments.each do |comment| %>
          <h3><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h3>
          <div class="feeds-comment-score comment-score<%= comment.score %>">
            <span class="glyphicon glyphicon-heart heart1"></span>
            <span class="glyphicon glyphicon-heart heart2"></span>
            <span class="glyphicon glyphicon-heart heart3"></span>
            <span class="glyphicon glyphicon-heart heart4"></span>
            <span class="glyphicon glyphicon-heart heart5"></span>
          </div>
          <p><%= comment.content %></p>
          <p class="user-name">by <%= link_to comment.user.name, user_path(comment.user) %></p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/restaurants/index.html.erb
<div class="container-fluid">

  <ul class="nav nav-tabs my-tabs">
    <li role="presentation" class="active"><%= link_to "首頁", restaurants_path %></li>
    <li role="presentation"><%= link_to "最新動態", feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to "Top10人氣餐廳", ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to "美食達人", users_path %></li>
  </ul>

  <br>

  <ul class="nav nav-pills nav-pills-center">
    <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
    <% @categories.each do |category| %>
      <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
  <br>

  <%= render partial: "shared/restaurant_list" %>

  <div class="text-center"><%= paginate @restaurants %></div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container-fluid">

  <ul class="nav nav-tabs my-tabs">
    <li role="presentation"><%= link_to "首頁", restaurants_path %></li>
    <li role="presentation"><%= link_to "最新動態", feeds_restaurants_path %></li>
    <li role="presentation" class="active"><%= link_to "Top10人氣餐廳", ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to "美食達人", users_path %></li>
  </ul>
  <br>

  <div class="panel panel-default">
    <div class="panel-heading my-panel-heading">
      <div class="panel-title"><h3>Top 10 人氣餐廳</h3></div>
    </div>
    <div class="panel-body ranking-panel-body">
      <% @top10_restaurants.each do |restaurant| %>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default my-label"><%= restaurant.category.name %></p>
        <p class="label label-default favorites_count_label">
          <span class="glyphicon glyphicon-star"></span>
          <%= restaurant.favorites_count %></p>
        <p><%= restaurant.description %></p>
        <hr>
      <% end %>
    </div>
  </div>

</div>

app/views/restaurants/show.html.erb
<h1 class="show-title"><%= @restaurant.name %></h1>
<h4 class="show-subtitle"><%= @restaurant.category.name %></h4>
<%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
<% if average_score(@restaurant) > 0 %>
  <div class="title-score">
    <span class="glyphicon glyphicon-heart title-heart"></span>
    <p><%= average_score(@restaurant) %></p>
  </div>
<% end %>

<div class="well">
  <div class="row">
    <div class="col-xs-5 col-md-6">
      <h3 class="show-content-title">Tel</h3>
    </div>
    <div class="show-content-detail col-xs-7  col-md-6">
      <p><%= @restaurant.tel %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5 col-md-6">
      <h3 class="show-content-title">Address</h3>
    </div>
    <div class="show-content-detail col-xs-7 col-md-6">
      <p><%= @restaurant.address %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5 col-md-6">
      <h3 class="show-content-title">Opening Hours</h3>
    </div>
    <div class="show-content-detail col-xs-7 col-md-6">
      <p><%= @restaurant.opening_hours %></p>
    </div>
  </div>
  <div class="text-right show-more-details">
    <%= link_to dashboard_restaurant_path(@restaurant) do %>
      More Details <span class="glyphicon glyphicon-arrow-right"></span>
    <% end %>
  </div>
</div>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10">
      <p class="lead"><%= @restaurant.description %></p>
    </div>
  </div>
  <div>
    <div class="show-image-frame">
      <% if @restaurant.image? %>
        <%= image_tag @restaurant.image, width: "100%" %>
      <% else %>
        <%= image_tag "http://fakeimg.pl/270x180/BBBBBB/", width: "100%" %>
      <% end %>
    </div>
  </div>
<br />

<% if current_user.admin? %>
  <div class="pull-right">
    <%= link_to edit_admin_restaurant_path(@restaurant), class: "show-icon btn btn-default" do %>
      <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    <%= link_to admin_restaurant_path(@restaurant),
      method: :delete, data: { confirm: "Are you sure?"}, class: "show-icon btn btn-default" do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </div>
<% end %>
<br>
<hr>

<div class="comment-area container-fluid">
  <% num = 1 %>
  <% @restaurant.comments.each do |comment| %>
    <div class="well">
      <% if comment.created_at %>  <!--make sure that it can render restaurants/show
        when the content of comment is empty-->
        <%= link_to user_path(comment.user) do %>
          <h4><%= comment.user.name %></h4>
        <% end %>
        <div class="comment-time"><p><%= time_ago_in_words(comment.created_at) %></p></div>
        <div class="comment-tag"><%= "# #{num}" %></div>
        <div class="seperate"></div>
        <div class="comment-score comment-score<%= comment.score %>">
          <span class="glyphicon glyphicon-heart heart1"></span>
          <span class="glyphicon glyphicon-heart heart2"></span>
          <span class="glyphicon glyphicon-heart heart3"></span>
          <span class="glyphicon glyphicon-heart heart4"></span>
          <span class="glyphicon glyphicon-heart heart5"></span>
        </div>
        <br>
        <div class="comment-content">
          <p><%= simple_format comment.content %></p>
        </div>
        <% if current_user.admin? or current_user == comment.user %>
          <div class="comment-delete">
            <%= link_to restaurant_comment_path(@restaurant, comment),
            method: :delete, data: { confirm: "Are you sure?"},
            class: "comment-delete-icon" do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
        <% end %>
        <% num += 1 %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="seperate"></div>

<div class="comment-form container-fluid">
  <% if !@restaurant.users.include?(current_user) %>
    <%= form_for [@restaurant, @comment] do |f| %>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <%= f.text_area :content, placeholder: "留個言吧" %>
        </div>
        <div class="col-xs-6 col-sm-6">
          <div class="score">
            <%= f.radio_button :score, 1, {class: "score1"} %>
            <%= f.radio_button :score, 2, {class: "score2"} %>
            <%= f.radio_button :score, 3, {class: "score3"} %>
            <%= f.radio_button :score, 4, {class: "score4"} %>
            <%= f.radio_button :score, 5, {class: "score5"} %>
            <span class="glyphicon glyphicon-heart heart1"></span>
            <span class="glyphicon glyphicon-heart heart2"></span>
            <span class="glyphicon glyphicon-heart heart3"></span>
            <span class="glyphicon glyphicon-heart heart4"></span>
            <span class="glyphicon glyphicon-heart heart5"></span>
          </div>
        </div>
        <div class="col-xs-6 col-sm-12">
          <%= f.submit class: "btn btn-default" %>
          <%= f.button "Cancel", type: :reset, class: "btn btn-default"%>
        </div>
      </div>
    <% end %>

  <% else %>
    <h4>The restaurant had been commented.</h4>
  <% end %>
</div>