config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :categories, only: :show

  resources :users, only: [:index, :show, :edit, :update] do

    member do
      get :friend_list
    end

  end

  resources :likes, only: [:create, :destroy]

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy] do

    member do
      post :confirm
    end

  end

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants, dependent: :restrict_with_error
  validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content, :score

  default_scope { order(created_at: :desc)}

  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: {scope: :user_id}

  belongs_to :user
  belongs_to :friend, class_name: "User"

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def update_favorites_count
    self.update(favorites_count: self.favorites.count)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error

  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :request_friend, through: :inverse_friendships, source: :user

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def send_request?(user)
    if self.friends.include?(user)
      self.friendships.find_by(friend_id: user.id).status == "request"
    else
      false
    end
  end

  def be_friend_with?(user)
    if self.friends.include?(user)
      self.friendships.find_by(friend_id: user.id).status == "confirm"
    else
      false
    end
  end

  def unconfirm_friends
    unconfirm_friendships = self.friendships.where(status: "unconfirm")
    unconfirm_friends = []
    unconfirm_friendships.each do |unconfirm_friendship|
      unconfirm_friends << User.find(unconfirm_friendship.friend_id)
    end
    return unconfirm_friends
  end

  def request_friends
    request_friendships = self.friendships.where(status: "request")
    request_friends = []
    request_friendships.each do |request_friendship|
      request_friends << User.find(request_friendship.friend_id)
    end
    return request_friends
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "comment was successfully created"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "comment and score cannot be blank"
      redirect_to restaurant_path(@restaurant, comment_params)
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin? or current_user == @comment.user
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :score)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = Like.create!(restaurant_id: params[:restaurant_id], user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.where(restaurant_id: params[:restaurant_id], user: current_user)
    like.destroy_all
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
  end

  def edit
    if current_user != @user
      flash[:alert] = "You are not allow to edit the profile"
      redirect_to user_path(@user)
    end

  end

  def update
    @user.update(user_params)
    flash[:notice] = "user profile was successfully updated"
    redirect_to user_path(@user)
  end

  def friend_list
    @unconfirm_friends = @user.unconfirm_friends
    @request_friends = @user.request_friends
  end

  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def average_score(restaurant)
    sum = 0
    if restaurant.comments.size > 0
      restaurant.comments.each do |comment|
        sum += comment.score if comment.score != nil
      end
      (sum.to_f / restaurant.comments.size).round(1)
    else
      0
    end
  end
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>餐廳評論網</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-left" do %>
            <span class="glyphicon glyphicon-home"></span>
          <% end %>
          <% if current_user %>
            <% if current_user.admin? %>
              <%= link_to admin_restaurants_path do %>
                <span class="glyphicon glyphicon-user"></span>
              <% end %>
            <% end %>
          <% end %>
          <div class="res-title">
            <p>Restaurant Forum</p>
          </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <div class="nav navbar-nav navbar-right">
            <% if current_user %>
              Hi, <%= current_user.email %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <button type="button" class="btn btn-default navbar-btn">登出</button>
              <% end %>
              <%= link_to edit_user_registration_path do %>
                <button type="button" class="btn btn-default navbar-btn">修改密碼</button>
              <% end %>
              <%= link_to user_path(current_user) do %>
                <button type="button" class="btn btn-default navbar-btn">Profile</button>
              <% end %>
            <% else %>
              <%= link_to new_user_registration_path do %>
                <button type="button" class="btn btn-default navbar-btn">註冊</button>
              <% end %>
              <%= link_to new_user_session_path do %>
                <button type="button" class="btn btn-default navbar-btn">登入</button>
              <% end %>
            <% end %>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      <% if flash[:notice] %>
        <div class="alert alert-warning alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"
          aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"
          aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if !restaurant.is_favorited?(current_user) %>
  <%= link_to favorite_restaurant_path(restaurant), method: :post,
  title: "adding to favorite list", class: "favorite-link" do %>
    <span class="glyphicon glyphicon-star favorite-icon"></span>
  <% end %>
<% else %>
  <%= link_to unfavorite_restaurant_path(restaurant), method: :post,
  title: "cancel from favorite list", class: "favorite-link" do %>
    <span class="glyphicon glyphicon-star unfavorite-icon"></span>
  <% end %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "Unfollow", followship_path(user), method: :delete,
    class: "btn btn-default btn-unfollow" %>
  <% else %>
    <%= link_to "Follow", followships_path(following_id: user), method: :post,
    class: "btn btn-default btn-follow" %>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.be_friend_with?(user) %>
    <%= link_to "Unfriend", friendship_path(user), method: :delete,
    class: "btn btn-default btn-unfollow" %>
  <% elsif current_user.send_request?(user) %>
    <%= link_to "Cancel", friendship_path(user), method: :delete,
    class: "btn btn-default btn-unconfirm" %>
  <% elsif user.send_request?(current_user) %>
    <%= link_to "Confirm", confirm_friendship_path(current_user, friend_id: user.id),
    method: :post, class: "btn btn-default btn-unconfirm" %>
  <% else %>
    <%= link_to "Friend", friendships_path(friend_id: user), method: :post,
    class: "btn btn-default btn-follow" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if !restaurant.is_liked?(current_user) %>
  <%= link_to "Like", likes_path(restaurant_id: restaurant.id), method: :post, class: "btn btn-primary" %>
<% else %>
  <%= link_to "Dislike", like_path(id: 0, restaurant_id: restaurant.id), method: :delete, class: "btn btn-info" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-sm-6 col-md-4">
      <div class="restaurant-item">
        <%if restaurant.image? %>
          <%= image_tag restaurant.image, class: "img-responsive center-block" %>
        <% else %>
          <%= image_tag "http://fakeimg.pl/270x180/FFFFBB/", class: "img-responsive center-block" %>
        <% end %>
        <div class="caption">
          <h3 class="text-center"><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <div>
            <% if average_score(restaurant) > 0 %>
              <div class="index-score">
                <span class="glyphicon glyphicon-heart index-heart"></span>
                <p><%= average_score(restaurant) %></p>
              </div>
            <% end %>
            <p class="label label-default my-label"><%= restaurant.category.name %></p>
          </div>
          <div class="truncated-description">
            <p><%= truncate(restaurant.description, length: 70) %></p>
          </div>
          <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
        </div>
      </div>
    </div>
  <% end %>
</div>